name: Stock Data Collection
on:
  schedule:
    # 미국 주식 시장 마감 후 데이터 수집 (한국 시간 기준 아침 6시)
    - cron: '0 21 * * 1-5'  
  workflow_dispatch:  # 수동 실행 옵션
jobs:
  collect-data:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/New_York'  # 미국 동부 시간대 설정
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install airtable-python-wrapper
        pip install pytz
    
    - name: Run collect_stock_data.py
      env:
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      run: python ./collect_stock_data.py
      
    - name: Run highest_traded_value.py
      env:
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      run: python ./highest_traded_value.py
      
    - name: Run Market Cap Leaders Collection (FMP)
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      run: python ./collect_market_cap.py
