name: Stock Data Collection

on:
  schedule:
    # 미국 주식 시장 마감 후 데이터 수집 (한국 시간 기준 아침 6시)
    - cron: '0 21 * * 1-5'  
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install airtable-python-wrapper
    
    - name: Run stock data collection script
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      run: python ./collect_stock_data.py

    - name: Run highest traded value script
      env:
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      run: python ./highest_traded_value.py
