name: Collect EPS Trend Data

on:
  workflow_dispatch:      # 수동 실행 가능

jobs:
  collect-eps-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas

    - name: Run EPS trend collection
      run: python collect_eps_trend.py
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add data/
        git commit -m "Update EPS trend data" -a || exit 0
        git push origin
